### ISSUE TITLE
Épico (Ocorrências)

### ISSUE THREAD

**Issue by vitmcalhau** [Johnssons/ProjetoMC426#14]
Eu, como usuário, gostaria de ter acesso aos casos relatados e suas informações, a fim de estar ciente dos crimes para planejar melhor meu caminho.

Histórias:
#15 #16

**Comment by brenofranca83** [comment]
Não há necessidade de listar atributos em épicos. Podem entrar nos critérios de aceite como itens obrigatórios ou não
