### ISSUE TITLE
História (Ocorrências) - Estatísticas

### ISSUE THREAD

**Issue by vitmcalhau** [Johnssons/ProjetoMC426#16]
Eu, como usuário, gostaria que fosse possível ver os casos relatados numa aba de estatísticas, por onde fosse possível utilizar filtros e categorias para visualizar os casos, a fim de possibilitar uma visão mais estatística e precisa.

Critérios de aceitação:
- Verifique se é possível visualizar apenas as ocorrências classificadas como 'Roubo'
- Verifique se, ao filtrar pelo período da manhã, aparecem ocorrências do período da tarde -> deveria falhar

**Comment by Johnssons** [comment]
This issue was solved in PR 26
